from setuptools import setup, find_packages

setup(
    name="emc_dynmap_bot",
    version="0.1.0",
    author="Zackareee",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",  # Replace with your license
        "Operating System :: OS Independent",
    ],
    packages=find_packages(),
    python_requires=">=3.12",  # Specify minimum Python version
    install_requires=[
        "aiohappyeyeballs",
        "aiohttp",
        "aiosignal",
        "alembic",
        "attrs",
        "black",
        "certifi",
        "charset-normalizer",
        "click",
        "colorama",
        "discord.py",
        "frozenlist",
        "greenlet",
        "idna",
        "iniconfig",
        "Mako",
        "MarkupSafe",
        "multidict",
        "mypy-extensions",
        "numpy",
        "packaging",
        "pandas",
        "pathspec",
        "pillow",
        "platformdirs",
        "pluggy",
        "propcache",
        "pytest",
        "python-dateutil",
        "pytz",
        "requests",
        "scipy",
        "shapely",
        "six",
        "SQLAlchemy",
        "tqdm",
        "typing_extensions",
        "tzdata",
        "urllib3",
        "yarl",
    ],
    extras_require={
        "dev": ["pytest", "mypy", "black", "mypy"],  # Additional dependencies for development
    },
    include_package_data=True,  # Includes non-Python files specified in MANIFEST.in
)
